### ISSUE TITLE
[UX] Touch, Mobile, Small screen/Scaled UI support

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#112]
As of Feb. 2016, touch-support is working and fully implemented.

The next steps is to make sure this is working on *all* platforms, then go ahead and implement responsive UIs so the interfaces scales better on mobile devices (or small screens).

If you have experience with design and want to participate, *please contact me*.

- [x] Touch Support
- [ ] Fix "script error" on gestures
- [x] Fullscreen app on <800px devices
- [ ] Scaled UI elements ?
- [ ] `gui-` element `data-responsive` attribute with "desktop" and "mobile" to trigger UI elements

**Comment by andersevenrud** [comment]
Interesting reads:
- http://www.stucox.com/blog/you-cant-detect-a-touchscreen/
- http://stackoverflow.com/questions/4817029/whats-the-best-way-to-detect-a-touch-screen-device-using-javascript
- https://github.com/Modernizr/Modernizr/issues/548

**Comment by andersevenrud** [comment]
@ComputeLinux @staticextasy

I have made some changes to the touch event binding. Could you check if you get the same problems [as in the past] when looking at the demo site ? Would be highly appreciated :smile:

**Comment by junland** [comment]
@andersevenrud Alright I was able to test a couple of devices, so here is what I found

Windows 8 Desktop - Worked fine, no problems with single or multi-windows open. (Firefox / Chrome)

Windows 8 Touch - I have a Dell touch screen monitor so I can test this out, no problems with any programs. Maybe a little lag here and there but that's probably because I have a very low spec VM running but we can probably get more optimization with later down the road. (Firefox / Chrome)

Android Tablet - Worked fine, little lag due to the VM and that it was transmitting over a saturated Wifi link but handled itself pretty well despite those conditions. Only thing that I couldn't use was the paint program to draw a happy face. Also note that it scaled well when I would go from portrait mode to landscape mode and I tried landscape to portrait. Although I did have a graphical glitch when I would separate two program windows and go to landscape to portrait. (Chrome)

![screenshot_2015-07-18-12-03-45](https://cloud.githubusercontent.com/assets/9792545/8762663/48966a08-2d45-11e5-860a-d6c611c13855.png)

![screenshot_2015-07-18-12-01-56](https://cloud.githubusercontent.com/assets/9792545/8762664/50349050-2d45-11e5-8398-1c9daedde423.png)

**Comment by andersevenrud** [comment]
@junland Awesome. More things I can check off the list :)

> Only thing that I couldn't use was the paint program to draw a happy face.

I knew I had forgotten to add [the newest] compability somewhere. Thanks. I'll fix that!

> Although I did have a graphical glitch when I would separate two program windows and go to landscape to portrait. (Chrome)

I have noticed this as well. You can actually replicate this using the Emulator in Chrome. It seems that Webkit has some problems with the overflow in some cases. I don't know if this is a bug or a problem I have created with my CSS... but will investegate this further.

**Comment by junland** [comment]
I found a JS library to handle touch, I know right now you can do it because touch is just emulating a mouse, but this library handles multi-touch and gestures. http://hammerjs.github.io/

**Comment by andersevenrud** [comment]
@junland I am familiar with that library (use it a lot at work). The things is, one of the things about OS.js is that it does not depend on any third-party stuff in the client core/default packages, and I think I want to keep it this way.

I however found something that could be used to write something custom. Under 200 lines and seem to work just as I want: https://github.com/rasismeiro/touch. Only downside is, no multi-touch... but I don't see any use of that in the current UI anyway.

This would mean that if a user wants more advanced touch support in their app, they'd have to include the script in the package.

What do you think about that ? :)

**Comment by junland** [comment]
@andersevenrud Ahhh yea that's fine. :)

**Comment by andersevenrud** [comment]
Windows 10 seems to introduce some problems, indeed. I need to create MSPointer event handling or something. Just tried on a Surface, and dragging did not work.

**Comment by junland** [comment]
@andersevenrud Where would the 3rd party libraries go? Let's say I wanted to add `io.js` (Just as a example)? Because I want to add bash support (Even though I can just do it with child process in pure js) I would like to add a js library where I can just call bash commands from the server. I might even just go ahead and just write a API call :).

**Comment by andersevenrud** [comment]
You have a couple of options:

### Add to preloader

Copy file into `dist/vendor/`. Then create a file named ex `src/conf/900-my-config.json` (or edit 110-frontend.json, but not recommended)

```

{
  "settings" : {
    "frontend" : {
      "Core" : {
        "Preloads":         {
          "my-library": {"type": "javascript", "src": "/vendor/my-library.js"}
        }
      }
    }
  }
}

```

Then run `grunt config`

### Add as an extension

http://os.js.org/doc/tutorials/extend-client-api.html

**Comment by andersevenrud** [comment]
FYI If you are planning on making something future-proff, I'd suggest using *gui-ng* branch to avoid any rewrites

**Comment by andersevenrud** [comment]
I am also changing the configuration stuff (simplified) in this branch, so a heads up there too.

**Comment by junland** [comment]
>You have a couple of options:

Awesome, and just specify `require(my-library.js:global)` in the main js files of the packages that require that specific package?

>FYI If you are planning on making something future-proff, I'd suggest using gui-ng branch to avoid any 
rewrites

Noted!

>I am also changing the configuration stuff (simplified) in this branch, so a heads up there too.

Cool!

**Comment by andersevenrud** [comment]
> Awesome, and just specify require(my-library.js:global) in the main js files of the packages that require that specific package?

You don't have to "load" anything. If it is set in the preloader or you are using an extension, everything is loaded by the time the desktop is initialized.

But if you are using requirejs, then just do the require() stuff in the Application code before you create any windows etc.

Ex: https://github.com/andersevenrud/OS.js-v2/blob/gui-ng/src/packages/default/About/main.js#L72

**Comment by junland** [comment]
@andersevenrud Got it!

**Comment by andersevenrud** [comment]
I am closing this issue in favour of #329.

This is something that will receive closer attention in the coming months (and I even have someone to help me this time), so look in #329 if you're interested in following the progress :)
