### ISSUE TITLE
[Applications] GoogleMail stuck in loading and misc errors

### ISSUE THREAD

**Issue by naltun** [os-js/OS.js#216]
As I am using the Google Mail v0.5 app, I am having crashes and unending loading screens.
I have encountered loading issues whilst loading my sent box and opening my contacts. I have encountered crash errors whilst I've been maneuvering around the app, and opening/closing it.

I'll continue tinkering around with Google Mail. Is there any particular way to document the issues?

---
- [ ] Loading issues
- [ ] Error when clicking inside views (undefined) #469

**Comment by andersevenrud** [comment]
Hi naltun,

The Google Mail app needs some work -- it has been far too long since I've looked at it as my priorities lies elsewhere at the moment :(

I will definately look into this when I have resolved all the other issues that has come in.

>  Is there any particular way to document the issues?

I think the information you provided should be enough for me to replicate and debug this.

**Comment by naltun** [comment]
:+1:  Sounds good. Let me know if I can help with anything.

**Comment by andersevenrud** [comment]
I'm closing this issue because it belongs to https://github.com/os-js/OS.js-extras and I'm going to retire the v2 applications pretty soon.

For the upcoming v3 release, I'm going to work on https://github.com/os-js/osjs-gmail-application (which is private at the moment) that will resolve all these issues.

Any further developments will be in the repository linked above. I'll make a notification here when it goes up.
