### ISSUE TITLE
[Applications] Word processor discussion

### ISSUE THREAD

**Issue by Esowteric** [os-js/OS.js#279]
Hi, I know that you have in mind, amongst many other things, the addition of a word processor.

Abiword is a light and useful word processor and it has things that writers need like open document and word doc support, and smart curly quotation marks. Abiword 3.0.1 is available for Linux and is based on GTK+ 3. The Windows binary only goes up to 2.8.6 but I'm told that 3.0.1 can be built for Windows.

I got the broadwayd server daemon running in an Ubuntu 15.04 VM. Things like gedit work fine, except for the fact that if a user closes the app in the web browser, it closes it on the server, too.

Abiword, however, didn't show and threw an exception, reporting: (abiword:3499): Clutter-Gtk-ERROR **: *** Unsupported backend.

I had a go at building LibreOffice to run in a web browser, but it's a bit of a monster and not easy for a novice. My build failed in the middle of the night when it found an EOF before an EOL. Perhaps my VM ran out of memory?

Collabora and OwnCloud have been working on getting a LibreOffice Live-based richdocuments app working in OwnCloud in a web browser (using API calls). An evaluation is available as a command-line only OpenSUSE VM which you can run in VirtualBox, but instructions for a manual build are largely “an exercise for the reader”, and building LibreOffice and the richdocuments app would be beyond most novice users or folk who just want to run software. The developers also report difficulties using the API.

You can find the Collabora Online Development Edition (CODE) at:
https://www.collaboraoffice.com/code/

I'm sure you have this covered already, but one thing that I noticed about gedit (for example) is that open and save gave access to the /home/ directory of the Linux user running broadwayd and other areas of the Linux file system – though fortunately access was denied due to a lack of permissions – whereas we'd of course want to be able to open and save to the OS.js user's home.

Thanks again for a great project!

Regards,
Eric Twose.

**Comment by andersevenrud** [comment]
> Hi, I know that you have in mind, amongst many other things, the addition of a word processor.

Oh, yes. This has been actually bothering me for quite a while. It's impossible to find a solution that integrates easily... most of the projects out there are not actual word processors, but small rich-text editors.

> I got the broadwayd server daemon running in an Ubuntu 15.04 VM. Things like gedit work fine, except for the fact that if a user closes the app in the web browser, it closes it on the server, too.

This is because you're streaming the applications. All interactions happens on the target computer :)

> I had a go at building LibreOffice to run in a web browser, but it's a bit of a monster and not easy for a novice. My build failed in the middle of the night when it found an EOF before an EOL. Perhaps my VM ran out of memory?

If you are planning on compiling LibreOffice, you need a shitload of RAM, hehe.

It seems that LibreOffice uses broadway just like OS.js to stream the app, so no need to build a custom one. Just use the binary.

https://wiki.documentfoundation.org/Using_LibreOffice_in_a_Web_Browser

> You can find the Collabora Online Development Edition (CODE) at:

I-ve looked at other alternatives as well. The thing about these online office suits is that they don't have an actual API and integration modules -- they come as one big and ready package. So there is no easy way to make use of it without just running it in an iframe or something like that, which kind of defeats the purpose.

> I'm sure you have this covered already, but one thing that I noticed about gedit (for example) is that open and save gave access to the /home/ directory of the Linux user running broadwayd – though fortunately access was denied due to a lack of permissions – whereas we'd of course want to be able to open and save to the OS.js user's home.

I will look into this

---

The thing is, I'd like to provide a OS.js native application (not broadway or stuff like that), but not been able to find any library for it. If you come across one, please let me know!

**Comment by Esowteric** [comment]
Thanks for your help and clarification, Anders.

**Comment by Esowteric** [comment]
Could you use the WebODF javascript library?
http://www.webodf.org/

**Comment by andersevenrud** [comment]
Interesting. It does not seem to support that many features, but it's something worth investegating. Thanks :)

**Comment by corbinu** [comment]
You could look into integrating this: https://www.collaboraoffice.com/code/ ... would also be good to support the own cloud instance as a private alternative to Google

**Comment by andersevenrud** [comment]
@corbinu Looks like a solid web framework there. Will have to investegate closer this weekend. Thanks! :)

**Comment by andersevenrud** [comment]
**THIS DISCUSSION HAS BEEN MOVED TO http://community.os.js.org/**
