### ISSUE TITLE
Try to type || in AceEditor application, end up with wierd image

### ISSUE THREAD

**Issue by XtremePlayzCODE** [os-js/OS.js#375]
I tried to type in || in AceEditor on OS.js and this weird half-circle thing on blue popped up. Anyway to fix this?

**Comment by andersevenrud** [comment]
Do you have a screenshot ?

**Comment by XtremePlayzCODE** [comment]
Yes, here ya go mister: http://imgur.com/C3LLjXE

**Comment by andersevenrud** [comment]
Ah. I see what is going on here. On you keyboard layout you have to press the SHIFT+TILDE key to get this symbol, which was actually the keyboard shortcut for the `Window Switcher` (like ALT+TAB in windows).

I have moved the shortcut to `ALT+TILDE` instead, since this does not produce any characters :) I also fixed so that the icons in the windowswitcher do not strech, like seen in your screenshot.

Also updated the demo server, but it is cached, so you might have to clear your browser.

Thanks :)

Ref: 6320266fbc4b8a1a5a74eaaf063a2698c5404b8d
