### ISSUE TITLE
FPS drops dramatically when moving a window with complex UI

### ISSUE THREAD

**Issue by VRspace4** [os-js/OS.js#387]
## Expected behaviour
When moving a window with complex UI, the rendering of the window should sustain an exceptable frame rate.

## Actual behaviour
Really slow fps

## Steps to reproduce the error
Create a window with lots of complex UI and then drag the title bar to move it.

## (Optinal) Browser and OS information
Chrome. Windows 10. 16GB RAM. Core i7-6600U.

## Suggested solution
When a move event initiates, render just the outline of the window and redraw completely when the user releases the mouse.

##

**Comment by VRspace4** [comment]
Is there a hardware accelerated rendering system that can be implemented?

**Comment by VRspace4** [comment]
This problem applies to resizing of the window as well.

**Comment by andersevenrud** [comment]
There's not much one can do about this,  because it heavly depends on your hardware, OS, drivers and browser vendor.

There might be a few tricks in CSS that could be applied to improve this, and could be benchmarked.

Another solution would be to have an option to disable live repaint of windows. So that you move/resize a transparent box instead of the  actual window (overlay) and it refreshes the window when you let go of the mouse button.

**Comment by andersevenrud** [comment]
One could also look into actually optimizing the code that handles these events. Maybe something has been overlooked.

**Comment by andersevenrud** [comment]
Can you send me the Scheme file ? I'd be interested in running some profiling on it

**Comment by VRspace4** [comment]
This isn't an issue. My CPU usage was probably really high from something else at that moment that caused the slowness.

**Comment by andersevenrud** [comment]
Allright! :)
