### ISSUE TITLE
[Arduino] cURL module not working properly on shipped Tian

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#396]
It seems that this third pary library has been going through a **lot** of changes, one of which is the name of the library.

Lua is case-sensitive, and loading "curl" will no longer work, "cURL" is the correct one.

*This was reported by a user via Gitter*

**This is not in any way a critical issue, but rather an annoyance for anyone seeking to develop apps**

**Comment by andersevenrud** [comment]
@sergiotomasello Could you get one of the guys to make an ipk of https://github.com/Lua-cURL/Lua-cURLv3 ? :)

I am having some trouble with luarocks for some unknown reason... can`t get it to work.

**Comment by artynet** [comment]
hello @andersevenrud, please find attached the ipk for Lua-cURLv3 both for Yun (running kernel v3.3.8 - 1209) ant Tian (running kernel v3.18.11 - 1505) :

[luacurl3_0.3.4-1-1209_ar71xx.ipk.zip](https://github.com/os-js/OS.js/files/265818/luacurl3_0.3.4-1-1209_ar71xx.ipk.zip)
[luacurl3_0.3.4-1-1505_ar71xx.ipk.zip](https://github.com/os-js/OS.js/files/265823/luacurl3_0.3.4-1-1505_ar71xx.ipk.zip)

please also consider that luarocks is basically useless because of the lua version running on the board (v5.1)

**Comment by sergiotomasello** [comment]
Thank you guys ;)

**Comment by andersevenrud** [comment]
It seems that 53d539a4dd06175c98da2271a136698e65227d64 solves the problem, accompanied with this ipk.

@nichis I will submit this to the Arduino Team ASAP

**Comment by andersevenrud** [comment]
A note for anyone that wants to hotfix this:


Edit /usr/lib/lua/osjs.lua. On line 39 and 40, change `require "curl"` to `require "cURL"`

Then:
```
# TIAN BOARDS
wget https://github.com/os-js/OS.js/files/265823/luacurl3_0.3.4-1-1505_ar71xx.ipk.zip
unzip luacurl3_0.3.4-1-1505_ar71xx.ipk.zip
opkg install luacurl3_0.3.4-1-1505_ar71xx.ipk
```
