### ISSUE TITLE
[v3] Multi-head

### ISSUE THREAD

**Issue by piranna** [os-js/OS.js#423]
Add support to use several browser windows to mimic/implement a multi-head system with several screen monitors. In a first step would be just enough to use window.open() function and postMessage() to comunicate between main and auxiliar windows (or better, move core functionality to a SharedWorker and windows doing requests to it), and in the long term allow to use windows on several independent devices (smartphone, tablet...) to extend the desktop area or show notifications or for an auxiliar tools panel.

**Comment by andersevenrud** [comment]
Hi!

This is something I really want to have implemented down the line. I'll see if I can't set up a branch and do some initial testing on this.

I've actually gotten quite a few questions/requests on this topic, so it might not be a bad idea to look into it sooner, rather than later.

Good ideas here. Thanks :)

**Comment by piranna** [comment]
You are welcome :-) I got on the point just this afternoon :-D Probably the
better is the SharedWorker path, since this would help to isolate the core
from the representation and help for the remote clients mostly by changuing
postMessage() for WebSockets :-)

**Comment by andersevenrud** [comment]
I might finally get to start the ball rolling on this now, as #617 is nearing completion. All of the recent changes should make this much, much easier :smile_cat:

**Comment by alalonde** [comment]
Any progress on this?  We have a related requirement where we'd like to embed OS.js inside of another app rather than it "owning" the entire web page.  There would be a number of changes to accommodate this, but one easy one is that there is a lot of styling, event-handling and UI appending that happens directly to the `<body>` element.  I am considering adding a `rootNode` concept or something to the config that defaults to `body` but can be overridden.  Then, OS.js interacts with this rather than the `<body>` element.

Any suggestions / obvious pitfalls with this?

**Comment by mds325** [comment]
That is a wonderful approach, it would be a good  improvement

**Comment by andersevenrud** [comment]
@alalonde Yeah, things are hard-coded to use the body, and so are certain events. So that's where it might get tricky. But it you wanna have a go, then by all means.

I'm working on v3 which has the options available to set it to whatever you want. Hence the reason there has not been activity in this spesific issue.

**Comment by SpaceboyRoss01** [comment]
It would be nice to get this working in BlueLight before `1.0.0-prealpha`.

**Comment by andersevenrud** [comment]
This issue has been moved here: https://github.com/os-js/osjs-client/issues/39
