### ISSUE TITLE
CDN for static content

### ISSUE THREAD

**Issue by msaqibansari** [os-js/OS.js#462]
Hi @andersevenrud,

I want to integrate CDN for all static content. I tried but when i pull files using CDN url like http://xxxxx.xxxx.netdna-cdn.com/packages/default/IVR/combined.css it gives error message "You have no OS.js Session, please log in!" but it worked when i  fetch file from root like http://xxxxx.xxxx.netdna-cdn.com/settings.js.

Please give me idea, how do i implement cdn.

Thanks

**Comment by andersevenrud** [comment]
This is because loading of package files are proxied through an authentication check. This is for the blacklisting/blocking of packages per-user functionality.

This occurs in the `Handler` on the server, more spesifically in this method: https://os.js.org/doc/server/Handler.Class.html#checkPackagePrivilege

You can override this method in your own handler

**Comment by andersevenrud** [comment]
Is this still unresolved ?

**Comment by andersevenrud** [comment]
I've added some stuff in branch `issue-462` that might help with this.

Package resources are now loaded using XHR with CORS (which means cookies are sent). This might fix this issue.

Can you test this ?

**Comment by andersevenrud** [comment]
I'm closing this issue due to lack of response. Feel free to re-open
