### ISSUE TITLE
[Applications] Settings - Rewrite

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#480]
The Settings application is something that has not changed much since the start of all of this. It's time to make it better.

One of the reasons is that I really want "pluggable" modules so it becomes easier to actually add/modify stuff.

I'm thinking something like the Gnome control panel thing.

Base:
- [x] Settle on some kind of design
- [x] Integrate design into base less file (generic CSS classes)
- [x] Module integration
- [x] SettingsManager Watches
- [x] Locales

Modules:

- [x] Theme
- [x] Desktop
- [x] Search
- [x] Sounds
- [x] Locales
- [x] VFS
- [x] Panels
- [x] User

New stuff:

- [x] Hotkey editor
- [x] Sound map editor
- [x] Package Manager
- [x] Mount Manager (TODO: Add more transports)
- [ ] Widgets
- [x] Store
- [x] User mangement

**branch:** https://github.com/os-js/OS.js/tree/development

~~**branch:** https://github.com/os-js/OS.js/tree/issue480~~

**Comment by marktopper** [comment]
How about something like this, including an option to add (or remove) setting groups.

![image](https://cloud.githubusercontent.com/assets/2232539/18559156/529ae9ea-7b76-11e6-91dc-7d34a2381878.png)

So then an application can put it's own settings in there.

**Comment by andersevenrud** [comment]
@marktopper Yeah. something like that!

**Comment by andersevenrud** [comment]
@marktopper It will be something among those lines, yes :) An early prototype:

![settings](https://cloud.githubusercontent.com/assets/161548/18686212/6b87436e-7f7b-11e6-9fa4-3a80a7b0d47d.png)

**Comment by marktopper** [comment]
@anderssevenrud: Look good, keep on the good work.

How will it look once you go into a setting group?
Have you decided that yet?

**Comment by andersevenrud** [comment]
@marktopper For now it will only be a "Save" and "Cancel" type button to bring you back. If you have any thoughts, please let me know.

**Comment by andersevenrud** [comment]
Another update
![settings2](https://cloud.githubusercontent.com/assets/161548/18703196/2bf32e56-7fe5-11e6-9e02-da5067f5ce6b.png)

**Comment by marktopper** [comment]
I don't think that there is a correct way to do for all of them since the content of them would be different.

Like those (taken from my Macbook Pro)

Desktop Settings (Select background and such)
<img width="676" alt="skaermbillede 2016-09-21 kl 11 27 22" src="https://cloud.githubusercontent.com/assets/2232539/18705450/902a0b5c-7fee-11e6-9b5d-922b71fe1f8c.png">

General Settings (Here OS.js could have general settings, like `Show File Extensions` and `Sounds`)
<img width="674" alt="skaermbillede 2016-09-21 kl 11 27 55" src="https://cloud.githubusercontent.com/assets/2232539/18705448/9027f4b6-7fee-11e6-901a-0609a35e1f28.png">

Language and Locales (Select Language)
<img width="674" alt="skaermbillede 2016-09-21 kl 11 28 08" src="https://cloud.githubusercontent.com/assets/2232539/18705449/9029a9d2-7fee-11e6-92d3-b76ce494c974.png">

**Comment by andersevenrud** [comment]
@marktopper For now it looks like this. Luckily it's very easy to modify.

![settings3](https://cloud.githubusercontent.com/assets/161548/18725441/95c86c0a-8040-11e6-9188-33dc9d009621.png)

**Comment by marktopper** [comment]
@andersevenrud: It's gonna be nice.

**Comment by andersevenrud** [comment]
This is now more or less done and ready for usage :)

You can check it out with the `developer` branch

**Comment by andersevenrud** [comment]
Well.... I'm calling this done for now and closing this issus. The remainding tasks already have individual issues.

Will merge into master as soon as it has been tested extensively :)
