### ISSUE TITLE
[Automated Bugreport] VARIOUS

### ISSUE THREAD

**Issue by D357** [os-js/OS.js#514]
## Expected behaviour

When clicking DeOS Shop it is sometimes crashes. When it doesn't crash, the store is empty.

On the information tab, it says twice that DeOS was launched in October 2015. This should say 2016. The info tab refers to dozens of features that are not on the DeOS desktop.

I don't know how or where to download it from but there doesn't seem to be a way to download a stand alone DeOS app for Windows or any other platform.

There is no integrated bitcoin wallet nor is it anywhere nearly clear how the 9000 DeOS tokens can be used. What are these tokens that I have bought for?
- 9.0 BTC is an awfully high amount to put on deposit if there tokens are only useable to by DeOS (it would be the largest amount I've ever spent on software by a few orders of magnitude)

There is no office suite other than an a Bgrade verson of Worspad and a Bgrade verson of Paint. If the software available to use on DeOS is so significantly less than what people are used to using, why would the use the DeOS apps?

There is no way to upload anything at all. No email client. No browser. No file transfer protocol or networking features of any kind 

It's nice that you have actually released something. It would be better if it was actually something close to a finished product - it's not even at beta as yet

**Comment by andersevenrud** [comment]
Hi,

I only found out about "DeOS" yesterday. It seems that Razormind is using OS.js as a product in which they are selling. So I won't be a ble to help you here -- since I am in no way affiliated with this organization -- I'm only the developer of OS.js, not "DeOS".

OS.js is actually alpha-software (which I have been developing in my spare-time since 2011) and has a lot of unfinished work.

You will have to contact Razormind (or whomever in charge) about your complaints and/or problems.
It seems that I also have to contact them, because they are linking directly to this Github repository evene though they've rebranded this as another product.

---

This was brought to my attention: https://bitcointalk.org/index.php?topic=1564499.0

**Comment by D357** [comment]
Bugger.  Thanks for the reply in any case.


On Sat, 22 Oct 2016 21:56:01 +1000, Anders Evenrud  
<notifications@github.com> wrote:

>
> Hi,
>
> I only found out about "DeOS" yesterday. It seems that Razormind is  
> using OS.js as a product in which they are selling. So I won't be a ble  
> to help you >here -- since I am in no way affiliated with this  
> organization -- I'm only the developer of OS.js, not "DeOS".
>
> OS.js is actually alpha-software (which I have been developing in my  
> spare-time since 2011) and has a lot of unfinished work.
>
> You will have to contact Razormind (or whomever in charge) about your  
> complaints and/or problems.
> It seems that I also have to contact them, because they are linking  
> directly to this Github repository evene though they've rebranded this  
> as another >product.
>
> This was brought to my attention:  
> https://bitcointalk.org/index.php?topic=1564499.0
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Using Opera's mail client: http://www.opera.com/mail/
