### ISSUE TITLE
[Applications] Music Player Statusbar & filename

### ISSUE THREAD

**Issue by taigrr** [os-js/OS.js#569]
Two closely related issues:

## Expected behaviour
UI should probably be dynamic, but it appears static.

## Actual behaviour
Slider slides to at most, 1:40. I tried playing a 3 minute song and I couldn't scrub to the end.
Also, the filenames on longer songs hang off the end of the UI box.

## Steps to reproduce the error

Play a song with a long filename for one issue, 

one longer than 3 min for the other

## (Optional) Browser and OS information

Latest Chrome x64, Win 10 Anniversary update

**Comment by andersevenrud** [comment]
The overflowing text should no longer be an issue.

**Comment by andersevenrud** [comment]
I am 100% sure that I've implemented HTTP1.1 partials (ranged content) correctly:

![httprangebytes](https://cloud.githubusercontent.com/assets/161548/23823484/09971d9e-0664-11e7-85e0-4817eae862e1.png)

So I am thinking that you were unable to seek because the slider was glitching out in some cases. I've done some improvements on that, so maybe that fixed your problem :)

**Comment by taigrr** [comment]
I'll check on it later today

**Comment by andersevenrud** [comment]
Closing this as I'm assuming everything is working.

Feel free to re-open if not.
