### ISSUE TITLE
Create app on php

### ISSUE THREAD

**Issue by DBplay** [os-js/OS.js#573]
Hi, I made a simple interface for configuring a web server. 
The OS.js interface is really incredible but i have a big problem. I have a fully developed application in PHP that communicates with a database and files located outside of the OS.js. 
And I unfortunately can't do it without using php. 
Is it possible to use the GUI of OS.js to communicate with the other system? I think I can use iframe but I do not think it's a clean solution.
Any idea even small will be helpful. Thank you in advance to help me with my problem.

**Comment by andersevenrud** [comment]
Hi,

Yes, you can use OS.js just as a "frontend" for your application.

There's both server-side (PHP and Node) and client-side (Javascript) code for the applications you make in OS.js, so you can implement pretty much anything.

If your web configuration application has some sort of API, it should be pretty easy to set up :)

**Comment by DBplay** [comment]
Probably I will sound stupid, but is it possible to have a very simple example ? Despite all my efforts I can not include an app in php.

**Comment by andersevenrud** [comment]
What do you mean by "include an app in php." exactly ?

**Comment by DBplay** [comment]
I apologize I made a mistake about term. I try to integrate directly the codes Php into an application.

**Comment by andersevenrud** [comment]
I don't know what your "code" is, though. Also, not sure what you mean by:

> Is it possible to use the GUI of OS.js

Do you mean the GUI toolkit OS.js provides (like, a "native" OS.js app), or do you just want to run your existing application inside a Window?

To break down both the methods:

1. Create a "OS.js application", using the GUI toolkits, etc. This involved adapting your existing codebase to run on OS.js. There's no single answer to "integrate existing application X into OS.js" because it depends entirely on how it was made. If your application is an API or a "library", then integration is pretty straight forward (just use the included examples when you make a new OS.js application), but if it is tightly integrated into something like Laravel or Symfony, using an iframe is probably a better choice.
2. Make an "iframe" application. This is the simplest choice, as it does not require to write any new code. You just run your app inside a window and it will behave just like a webpage. This can even run remotely.

**Comment by DBplay** [comment]
Thank you for these answers. At first time I am going to use an iframe, and secondly I rewrite them specifically for Os.js. thank you for your answer. Is it possible to donate somewhere ?

**Comment by andersevenrud** [comment]
You can find information about contributions and donations etc here: https://github.com/os-js/OS.js/blob/master/CONTRIBUTING.md :)
