### ISSUE TITLE
Error - TRying to update Yun

### ISSUE THREAD

**Issue by ganpheld** [os-js/OS.js#664]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://192.168.1.17/packages/target/ArduinoPackageManager/combined.js?31699:282:29
    at ArduinoHandler.<anonymous> (http://192.168.1.17/packages/target/ArduinoPackageManager/combined.js?31699:254:16)
    at ArduinoHandler.<anonymous> (http://192.168.1.17/osjs.js:1692:14)
    at Object.onerror (http://192.168.1.17/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.1.17/osjs.js:1202:16)
```

**Comment by ganpheld** [comment]
I also have an issue with the Wifi.    The yun looses its wifi connection every now and then.  Sometimes it comes back and sometimes it does not, I have to reboot.

**Comment by andersevenrud** [comment]
Yes, some boards seem to drop the connections intermittently, hence why you are getting this error. I  can't help you there since I'm not affiliated with Arduino in any way.

Try using Luci instead: http://arduino-ip/cgi-bin/luci if you want to configure the board or log into a shell to perform an upgrade manually.

I'm closing this issue because it's not an issue with OS.js. This error message is also tracked in a separate repository.
