### ISSUE TITLE
additional touch compatibility (paint, close windows, etc..)

### ISSUE THREAD

**Issue by MacroMachines** [os-js/OS.js#672]
in the example os, dragging windows and general behavior seems to work well with ios chrome, which would lead me to expect everything works with touch. 

click on buttons to minimize or close window > does nothing
tried paint app, paintbrush, select color works,  move finger in draw area > does nothing

**Comment by andersevenrud** [comment]
You can try the `development` branch. If I remember correctly, there's a few fixes in there. But yes, the current touch implementation is a bit buggy :/ I'm having a look at a proper solution for v3.

**Comment by andersevenrud** [comment]
Hi,

Just letting you know that touch support has been improved for the upcoming v3 release.
Any gestures etc. will be handled in the https://github.com/os-js/osjs-client repository from now on.

*Note*: iPhone/iPad (safari) has just recently been made compatible with v3 (today actually), which  gets an official npm release coming weekend.

So, for now I'm closing this issue because my main focus is on v3.
