### ISSUE TITLE
Automatic backup in clouds

### ISSUE THREAD

**Issue by OlivieBright** [os-js/OS.js#704]
It would be really cool to backup the clouds automatically. It would be interesting with Google Drive, Mega.nz, Mediafire, 4shared and others ... ^^

**Comment by SpaceboyRoss01** [comment]
There's a vfs adapter for google drive so you can just copy your files.

**Comment by andersevenrud** [comment]
As @SpaceboyRoss01 there's a VFS adapter for Google Drive, so that can be used to store files etc.

Because there's several ways to connect and store users/settings(database, filesystems, memory, etc.) it  should probably be up to the system administrator to set up backup, mirroring, etc.

I think MEGA has some sort of API, so it would probably be interesting to looking into adding that as an adapter.
