### ISSUE TITLE
Allow execution of shell scripts

### ISSUE THREAD

**Issue by 17lwinn** [os-js/OS.js#733]
Maybe you could make an app that runs shell scripts?

I mean by this is some sort of app that runs .sh or .c scripts by default?

----

This was raised before i know but perhaps it could be an idea to put into V3?

**Comment by andersevenrud** [comment]
It's possible for developers to run any arbitrary script using either the application server script, or this on the client side https://github.com/os-js/osjs-proc-provider.

However, making it possible for users to run arbitrary scripts is a security issue because these will spawn on the server. This means that anyone could upload a script that attempts to modify files on the host system or inject a virus or something.

**Comment by 17lwinn** [comment]
I understand, thanks for the help

**Comment by andersevenrud** [comment]
No problem :)
