### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by donatme** [os-js/OS.js#734]
gmail send dont work

**Comment by RossComputerGuy** [comment]
Care to explain more?

**Comment by andersevenrud** [comment]
I'm assuming the submitter of this issue was having troubles with the Gmail application provided in the v2 demo.

Sadly, this no longer works due to changes in the Google APIs. And there are no plans to update this.

However, a newly written app for v3 will soon be available  -- and the demo site will be switched to v3 by default soon as well.

Because of these reasons, I'm closing this issue.
