### ISSUE TITLE
browser app?

### ISSUE THREAD

**Issue by 17lwinn** [os-js/OS.js#749]
Hi, i was wondering if there was a browser app for os.js? i have found one but seems to throw a lot of errors about css styling and all that.

**Comment by andersevenrud** [comment]
It's not really possible to have a browser in a browser app because of the security policies (iframes).

There are some exploits that makes it possible to load web pages and get around some of these policies, but generally makes heavily dynamic and scripted pages unusable.

Example implementation: https://gist.github.com/andersevenrud/ef2194494b00f936f3ce8030084754b8

On an Electron environment it's possible to use something like https://www.electronjs.org/docs/api/browser-view or maybe a webview with some glue.

**Comment by andersevenrud** [comment]
> or maybe a webview with some glue.

Though this is probably not recommended as it's single process.
