### ISSUE TITLE
Why is my docker version outdated?

### ISSUE THREAD

**Issue by NideZ60** [os-js/OS.js#772]
When i use the latest docker, its running an older and less useful version than the demo! why is this? and i have no point in the docker if i can use the demo with more features....

**Comment by andersevenrud** [comment]
Are you referring to https://github.com/os-js/OS.js#demo VS https://demo.os-js.org/ ?

**Comment by andersevenrud** [comment]
Looks like some of my external CI triggers didn't function properly. There should be new Docker Hub images available within 30 minutes.

In case you were referring to the online demo missing things like certain apps, then this is because it's running a custom setup based on the docker image. It's simply a base image that ships with the same features as the repository if you were to install it manually.

You can create your own images like that by creating your own Dockerfile. Example:

```dockerfile
FROM osjs/osjs:latest
RUN npm install @osjs/ace-application @osjs/pdfreader-application
RUN npm run package:discover
```

**Comment by andersevenrud** [comment]
I've updated the README a little bit to clarify this.
