### ISSUE TITLE
Running without npm

### ISSUE THREAD

**Issue by Destuxer** [os-js/OS.js#773]
I'm a teensy bit lacking when it comes to web programming, but wouldn't it be easier to run a (pre-built with npm) package via an index.html file?
That way there's no need to install the OS, just have to have the dependencies included in the package.

**Comment by andersevenrud** [comment]
You actually can do this. Here's an example with codepen: https://codepen.io/andersevenrud/pen/GzWoeN

However, this does not automatically include applications because these are intended to be hosted together with your index.html file "and all the rest", so it requires some manual configuration to get going over for example a CDN. This repo comes with tools that does all that stuff for you.

Another thing is that this repo also comes with a server-side API that provides the standard filesystems, authentication and a bunch of other stuff.

This repo is designed to roll your own setup so that you can use it however you want (including the use-case you described).

**Comment by andersevenrud** [comment]
I forgot:

Running it like you described requires to put the client into a "standalone" mode. Which basically disables the default server API stuff and lets you run "freely".

**Comment by Destuxer** [comment]
Yeah, I don't really need to run it on a server, just need to run it on my local machine in the browser.

**Comment by andersevenrud** [comment]
Closing this one beacuse of inactivity. Feel free to re-open.
