### ISSUE TITLE
Security consideration in OSjs

### ISSUE THREAD

**Issue by mahsashadi** [os-js/OS.js#806]
Have any **security consideration** been taken into account so far? especially for third-party applications.

**Comment by andersevenrud** [comment]
There really is no way to sandbox the node runtime, so any security issue you would get from any third party package applies here.

In the client, it's possible to sandbox things in an iframe, but you can still write glue code to interact with the API.

That said, there are some configuration options to lock down access to certain global stuff.

**Comment by mahsashadi** [comment]
> That said, there are some configuration options to lock down access to certain global stuff.

I didn't get this line, would you please give an example?

**Comment by andersevenrud** [comment]
> I didn't get this line, would you please give an example?

The global `OSjs` variable is immutable and there are ways to block access to certain service providers on the `make` method. But this won't stop anyone from going in and overriding other parts of the code.

It's very hard to harden the client code without creating code that is inefficient and hard to maintain without using frames or workers for everything :/

**Comment by andersevenrud** [comment]
Closing this issue because any security advice I'd give here is what you should follow in general for writing web apps. And on top of that list is not to trust third party stuff.

Since OS.js uses npm packages and does not have any APIs (currently) to manage these it's fairly hard to accidentally be exposed to a security risk. It's all operated by the end-user or maintainer of the installation.

Could maybe be discussed further in https://github.com/os-js/OS.js/discussions if someone has ideas around this.
