### ISSUE TITLE
Use Notification in login osjs

### ISSUE THREAD

**Issue by parhamsagharchi** [os-js/OS.js#811]
Hello,

well, I would like to ask about how we can use notification on the login window?, on other words, I want to indicate the message of auth (a message generated from API) to users. especially when auth process will be failed.

I know how can I use notification in the application but when I want to use this way to server "osjs" I could do that.

thanks

**Comment by andersevenrud** [comment]
I think it's possible to enable notifications without desktop by changing your service provider registration to:

```js
  osjs.register(NotificationServiceProvider, {before: true});
```

Now you can access the API just like in applications. You have to create your own login adapter though, because the default one does not have any way to provide notifications from backend.

**Comment by parhamsagharchi** [comment]
Thank You,

**Comment by andersevenrud** [comment]
Closing as this seems resolved. If not, feel free to re-open :blush:
